name: Build Scamsung kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Aggressive cleanup
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Cleanup space"

        (docker system prune -af && docker builder prune -af || true) &

        DIRS=(
          /usr/share/dotnet
          /usr/share/swift
          /usr/local/.ghcup
          /usr/local/julia*
          /usr/local/lib/android
          /usr/local/share/chromium
          /opt/microsoft
          /opt/google
          /opt/az
          /usr/local/share/powershell
          /opt/hostedtoolcache
        )

        printf "%s\0" "${DIRS[@]}" | xargs -0 -P 4 -n 1 sudo rm -rf

        wait
        df -h
        echo "::endgroup::"

    - name: Setup SWAP
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 16

    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc bison flex libssl-dev make libncurses5-dev git curl clang lld \
        libelf-dev erofs-utils android-sdk-libsparse-utils build-essential automake autoconf libtool pkg-config fuse3 e2fsprogs pv liblz4-dev uuid-dev \
        libfuse3-dev fuse3 f2fs-tools fuse2fs attr zlib1g-dev rsync \
        device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full \
        pv uuid-dev libfuse3-dev f2fs-tools fuse2fs attr

    - name: Add KernelSUNext
      run: |
        cd "kernel-5.10"
        curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s dev

        ./scripts/config --file arch/arm64/configs/a17_00_defconfig \
          -e CONFIG_KSU

        cd "KernelSU-Next"
        git fetch origin dev 2>/dev/null || true
        KSU_GIT_VERSION=$(git rev-list --count refs/remotes/origin/dev 2>/dev/null)
        KSU_GIT_TAG=$(git describe --tags --abbrev=0 refs/remotes/origin/dev 2>/dev/null || echo "")
        KSU_COMMIT=$(git rev-parse --short refs/remotes/origin/dev 2>/dev/null)
        KSU_VERSION=$((30000 + KSU_GIT_VERSION))

        cd kernel
        sed -i "s/^KSU_VERSION_FALLBACK := 1$/KSU_VERSION_FALLBACK := ${KSU_VERSION}/" Kbuild
        sed -i "s/^KSU_VERSION_TAG_FALLBACK := v0.0.1$/KSU_VERSION_TAG_FALLBACK := ${KSU_GIT_TAG}/" Kbuild

    - name: Build Kernel
      run: |
        chmod +x build_kernel.sh
        ./build_kernel.sh

    - name: Create boot image
      run: |
        cd "tools"
        unzip boot.zip
        ./magiskboot unpack boot.img
        cp ../out/target/product/a17/obj/KERNEL_OBJ/kernel-5.10/arch/arm64/boot/Image kernel
        ./magiskboot repack boot.img
        mv new-boot.img boot.img

    - name: Create boot image tar
      run: |
        cd "tools"
        tar -cvf "boot.tar" boot.img

    - name: Upload Dist Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "Scamsung A17 Boot Image and Tar archive"
        path: |
          ./tools/boot.img
          ./tools/boot.tar
        if-no-files-found: ignore
        retention-days: 3